linters:

  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 1

  BorderZero:
    enabled: true
    convention: 0

  ChainedClasses:
    enabled: false

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    allowed: '\/\*[\s\S]*\n\!doc \*\/gm'

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: true
    ignore_consecutive:
      - background
      - transition
      - margin
      - padding
      - border

  ElsePlacement:
    enabled: true
    style: same_line

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: false # CSS should imply the HTML structure

  ExtendDirective:
    enabled: true # Extends are bad practice

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: lowercase

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: false # !important is bad, _except_ for immutability

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    enabled: true
    width: 2
    character: space
    allow_non_nested_indentation: false

  LeadingZero:
    enabled: true
    style: exclude_zero

  LengthVariable:
    enabled: true
    #allowed_lengths
    #allowed_properties

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true # for private vars
    convention: hyphenated_lowercase

  NestingDepth:
    enabled: true
    max_depth: 3

  PlaceholderInExtend:
    enabled: false # not needed, extends are disabled

  PrivateNamingConvention:
    enabled: true
    prefix: "_"

  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 8 # this is liable to change in the future

  PropertySortOrder:
    enabled: true
    min_properties: 2

  PropertySpelling:
    enabled: true

  PropertyUnits:
    enabled: true
    global: ['em', 'rem', '%']
    properties: # will be updated
      line-height: []
      border: ['px', 'em']
      margin: ['em', 'rem']
      padding: ['em', 'rem']

  PsuedoElement:
    enabled: true

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true # allow selectors for WAI-ARIA

  SelectorDepth:
    enabled: true
    max_depth: 3

  # Needs discussion.
  # SelectorFormat:
  #   enabled: true
  #   convention: hypenated_lowercase

  Shorthand:
    enabled: true

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableColon:
    enabled: true
    style: one_space

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: true
    style: space

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: true
    properties:
      - color
      - font
      - padding
      - margin

  VendorPrefix:
    enabled: true

  ZeroUnit:
    enabled: true
